// export const weatherKeywords = {
// 	'clear sky': 'clear',
// 	'few clouds': 'partly cloudy',
// 	'scattered clouds': 'partly cloudy',
// 	'broken clouds': 'cloudy',
// 	'overcast clouds': 'overcast',
// 	'light rain': 'rain',
// 	'moderate rain': 'rain',
// 	'heavy intensity rain': 'rain',
// 	'very heavy rain': 'rain',
// 	'extreme rain': 'rain',
// 	'freezing rain': 'rain',
// 	'light snow': 'snow',
// 	'moderate snow': 'snow',
// 	'heavy snow': 'snow',
// 	'sleet': 'sleet',
// 	'shower rain': 'rain',
// 	'thunderstorm': 'thunderstorm',
// 	'thunderstorm with light rain': 'thunderstorm',
// 	'thunderstorm with rain': 'thunderstorm',
// 	'thunderstorm with heavy rain': 'thunderstorm',
// 	'light thunderstorm': 'thunderstorm',
// 	'heavy thunderstorm': 'thunderstorm',
// 	'ragged thunderstorm': 'thunderstorm',
// 	'thunderstorm with light drizzle': 'thunderstorm',
// 	'thunderstorm with drizzle': 'thunderstorm',
// 	'thunderstorm with heavy drizzle': 'thunderstorm',
// 	'mist': 'fog',
// 	'smoke': 'smoke',
// 	'haze': 'haze',
// 	'sand/ dust whirls': 'dust',
// 	'fog': 'fog',
// 	'sand': 'dust',
// 	'dust': 'dust',
// 	'volcanic ash': 'ash',
// 	'squalls': 'windy',
// 	'tornado': 'tornado'
// };